version: '3.1'

services:

  drupal:
    restart: always
    image: drupal:9.3.2-php7.4-apache-buster
    ports:
      - "80:80"
    volumes:
      - ./:/opt/drupal/web
    links:
      - mysql
      - smtp

  mysql:
    restart: always
    # Use root/example as user/password credentials
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    command: --max_allowed_packet=100M

    environment:
      MYSQL_DATABASE: $$db_name$$
      MYSQL_ROOT_PASSWORD: $$db_passwd$$

    ports:
      - "3306:3306"

    volumes:
      - /opt/drupal/infraportal.sql:/docker-entrypoint-initdb.d/infraportal.sql
      - dbdata-dev:/var/lib/mysql

  smtp:
    restart: always
    image: rnwood/smtp4dev
    ports:
      - "2580:80"
      - "2525:25"
    volumes:
      - smtpdata:/smtp

volumes:
  dbdata:
  smtpdata:
