version: '3.1'

services:

  drupal:
    restart: always
    image: drupal:9.3.2-php7.4-apache-buster
    ports:
      - "80:80"
    volumes:
      - ./:/opt/drupal/web
    links:
      - smtp

  smtp:
    restart: always
    image: rnwood/smtp4dev
    ports:
      - "2580:80"
      - "2525:25"
    volumes:
      - smtpdata:/smtp

volumes:
  smtpdata:
